local map = vim.keymap.set
local silent = { silent = true }

map("c", "<C-g>", "<C-c>")
map("c", "<C-a>", "<C-b>")
map("i", "<C-d>", "<Delete>")
map("i", "<C-h>", "<BS>")
map("i", "<C-f>", "<Right>")
map("i", "<C-b>", "<Left>")
map("i", "kj", "<Esc>", silent)
map("i", "<C-v>", "<C-r>+")
map("n", "Q", "<Nop>")
map("n", "gQ", "<Nop>")
map("n", "<Esc><Esc>", "<Cmd>nohlsearch<CR>", silent)
map("n", "k", "gk")
map("n", "+", "g;")
map("n", "J", "gJ")
map("n", "zc", "zz", { desc = "Center current line" })
map("n", "zj", "<C-e>", { desc = "Scroll view down" })
map("n", "zk", "<C-y>", { desc = "Scroll view up" })
map("n", "mm", "%", { desc = "Jump to matching bracket" })
map("n", "ms", "ys", { desc = "Add surround", remap = true })
map("n", "mr", "cs", { desc = "Replace surround", remap = true })
map("n", "md", "ds", { desc = "Delete surround", remap = true })
map("n", "ma", "va", { desc = "Select around textobject", remap = true })
map("n", "mi", "vi", { desc = "Select inside textobject", remap = true })

map("n", "<leader>.", "<Cmd>edit!<CR>", { desc = "Reload file" })
map("n", "<leader>w", "<Cmd>write<CR>", { desc = "Write file" })
map("n", "<leader>q", "<Cmd>quit!<CR>", { desc = "Force quit" })
map("n", "<leader>c", function() vim.fn.setreg("+", vim.fn.expand("%:p")) end, { desc = "Copy file path" })
map("n", "<leader>C", function() vim.fn.setreg("+", vim.fn.getcwd()) end, { desc = "Copy cwd" })
map({ "n", "x" }, "<leader>p", '"+p', { desc = "Paste clipboard after" })
map({ "n", "x" }, "<leader>P", '"+P', { desc = "Paste clipboard before" })
map({ "n", "x" }, "<leader>y", '"+y', { desc = "Yank to clipboard" })
map("n", "<leader>Y", '"+Y', { desc = "Yank line to clipboard" })
