config-version = 2
start-at-login = true
after-startup-command = ['layout tiles']
persistent-workspaces = ['1', '2', '9']
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[key-mapping]
preset = 'qwerty'

[workspace-to-monitor-force-assignment]
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']
6 = ['secondary', 'main']
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['built-in', 'main']

[mode.main.binding]
alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'
alt-shift-6 = 'workspace 6'
alt-shift-7 = 'workspace 7'
alt-shift-8 = 'workspace 8'
alt-shift-9 = 'workspace 9'
alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'
alt-ctrl-8 = 'move-node-to-workspace 8'
alt-ctrl-9 = 'move-node-to-workspace 9'
alt-shift-space = 'layout floating tiling'
alt-shift-f = 'fullscreen'
alt-shift-s = 'join-with down'
alt-shift-v = 'join-with right'
alt-shift-enter = 'exec-and-forget /usr/bin/open -na Ghostty.app'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1'
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 2'
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3'
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 9'
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 8'
